# Generated by Django 3.2.5 on 2021-07-13 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0003_auto_20210713_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz_app.question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_app.category'),
        ),
    ]
